### PR TITLE
Change default username to osism

### PR DESCRIPTION
**Pull request by osfrickler**
Let's have some branding and use osism as username.

Add a small comment about possible issue during installation.

Closes: #33 

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

### CODE REVIEW

**Comment by berendt** [comment]
We should then mention in the deployment guide that the user must be osism instead of ubuntu when using the node image.

**Comment by osfrickler** [comment]
I checked and didn't find any reference to the username inside any documentation other than the README changed in this patch. Do you have a pointer to another location that needs an update?

**Comment by berendt** [comment]
https://docs.osism.tech/deployment/bootstrap.html

```osism apply operator -u ubuntu```

I think this is the only place.

**Comment by osfrickler** [comment]
> https://docs.osism.tech/deployment/bootstrap.html
> 
> `osism apply operator -u ubuntu`
> 
> I think this is the only place.

Ah, I didn't find it because node-image is mentioned only in the provisioning section. The tricky thing here is that we document installing from upstream images as a second option and there we create the user "ubuntu". Do you want to update that doc, too (incl. screenshots)? Or rather introduce a variable into the bootstrap doc?

**Comment by berendt** [comment]
> > https://docs.osism.tech/deployment/bootstrap.html
> > `osism apply operator -u ubuntu`
> > I think this is the only place.
> 
> Ah, I didn't find it because node-image is mentioned only in the provisioning section. The tricky thing here is that we document installing from upstream images as a second option and there we create the user "ubuntu". Do you want to update that doc, too (incl. screenshots)? Or rather introduce a variable into the bootstrap doc?

Copy & paste should be possible. I would then prefer to also change the manual instructions. There is already an open issue for the revision of the screenshots, since they are all still from Ubuntu 20.04.

**Pull request merged**
